services:
  mysql-primary.mysql.svc.cluster.local:   # I made such a service name for mysql container because in that case I do not need to change application.properties file.
    image: mysql:8.0.0
    container_name: mysql
    env_file:
    - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}             ### used the database name as bankappdb
    ports:
    - "3306:3306"
    deploy:
      resources:
        limits: 
          cpus: "0.5"
          memory: "512M"
        reservations: 
          cpus: "0.25"
          memory: "256M"
    restart: always 
    volumes:
    - db_data:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: Dockerfile-Project-1
    image: ${REPO_NAME}:${TAG_NAME}
    container_name: bankapp
    env_file:
    - ./.env
    depends_on:
      - mysql-primary.mysql.svc.cluster.local
    environment:
      JDBC_URL: jdbc:mysql://mysql-primary.mysql.svc.cluster.local:3306/bankappdb?useSSL=false&serverTimezone=UTC
      JDBC_USER: root
      JDBC_PASS: ${MYSQL_ROOT_PASSWORD}
    ports:
    - "8080:8080"
    pull_policy: never
    deploy:
      resources:
        limits: 
          cpus: "0.5"
          memory: "512M"
        reservations: 
          cpus: "0.25"
          memory: "256M"
    restart: always
volumes:
  db_data:
x-default-logging: &logging     ### For extracting Containers Logs
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
