FROM eclipse-temurin:17-jdk-alpine
MAINTAINER "Dexter"

RUN mkdir -p /usr/local/newrelic
ADD ./newrelic/newrelic.jar /usr/local/newrelic/newrelic.jar
ADD ./newrelic/newrelic.yml /usr/local/newrelic/newrelic.yml

WORKDIR /usr/src/app
COPY target/*.jar ./app.jar
EXPOSE 8080
CMD ["java", "-javaagent:/usr/local/newrelic/newrelic.jar", "-jar", "app.jar"]
